kind: Service
apiVersion: v1
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
spec:
  selector:
    app: strimzi-cluster-operator
  type: NodePort
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092