quarkus:
  http:
    port: 9090
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: orders123
  flyway:
    migrate-at-start: true
mp:
  messaging:
    outgoing:
      orders:
        connector: smallrye-kafka
        topic: orders-topic
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer