quarkus:
  application:
    name: assets-order
  http:
    root-path: /order
    port: ${PORT:9090}
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${POSTGRES_USER:orders}
    password: ${POSTGRES_PASSWORD:orders123}
  flyway:
    migrate-at-start: true
mp:
  messaging:
    outgoing:
      orders:
        connector: smallrye-kafka
        topic: orders-topic
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer