apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: assets-order-postgres
  namespace: dev
spec:
  rules:
    - http:
        paths:
          - path: /order
            backend:
              serviceName: assets-order
              servicePort: 8080
