apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-order-postgres
  namespace: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-order-postgres
  namespace: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/postgres-data"
    type: DirectoryOrCreate