quarkus:
  application:
    name: assets-balance
    http:
      root-path: /balance
      port: ${PORT:9091}
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/balance}
    username: ${POSTGRES_USER:balance}
      password: ${POSTGRES_PASSWORD:balance123}
  flyway:
    migrate-at-start: true
mp:
  messaging:
    incoming:
      orders:
        connector: smallrye-kafka
        topic: orders-topic
        value:
          deserializer: com.demo.balance.BalanceDeserializer