quarkus:
  http:
    port: 9091
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5433/balance
    username: balance
    password: balance123
  flyway:
    migrate-at-start: true
mp:
  messaging:
    incoming:
      orders:
        connector: smallrye-kafka
        topic: orders-topic
        value:
          deserializer: com.demo.balance.BalanceDeserializer